parameters:
    loremweb_ticketmanager:
        date:
            past_dates: false #ok
            days_closed: [0, 6] #ok
            date_closed: ["05-01", "12-25"] #ok
        nb_tickets_max: 10 #ok
        tarifs:
            normal: [12, 60, 16]
            enfant: [4, 12, 8]
            senior: [60, 200, 12]
            gratuit: [0, 4, 0]
        reduit: [10]

services:
#    loremweb_ticketmanager.example:
#        class: Loremweb\Bundle\TicketmanagerBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    loremweb__ticketmanager.services.gestion_tunnel_achat:
        class: Loremweb\Bundle\TicketmanagerBundle\Services\GestionTunnelAchat
        arguments: [ "@doctrine.orm.entity_manager", "@form.factory", "@session", "%loremweb_ticketmanager%" ]

    validator.date_valide:
        class: Loremweb\Bundle\TicketmanagerBundle\Validator\Constraints\DateValideValidator
        arguments: [ "%loremweb_ticketmanager%" ]
        tags:
            - { name: validator.constraint_validator }
    twig_ajout:
        class: Loremweb\Bundle\TicketmanagerBundle\Services\TwigAjout
        public: true
        tags:
            - { name: twig.extension }
