<?php

namespace Loremweb\Bundle\TicketmanagerBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPlacesRestantesSelonDates()
    {
        $query = $this->_em->createQuery('SELECT r.dateVisite, SUM(r.nombreBillet) FROM LoremwebTicketmanagerBundle:Reservation r GROUP BY r.dateVisite');
        $result = $query->getResult();

        $placeParDates = [];
        $placeParJour = 10;

        foreach ($result as $el) {
            if ($el[1] < 0) {
                $el[1] = 0;
            }

            $placeRestante = $placeParJour - $el[1];
            $placeParDates[$el['dateVisite']->format('Y-m-d')] = $placeRestante;
        }



        return json_encode($placeParDates);
    }

    public function getPlacesRestantesSelonDate($dateVisite)
    {
        $query = $this->_em->createQuery('SELECT r.dateVisite, SUM(r.nombreBillet) FROM LoremwebTicketmanagerBundle:Reservation r WHERE :dateVisite')
        ->setParameter('date', $dateVisite );
        $result = $query->getResult();

        $placesRestantes = $result[1];

        return $placesRestantes;
    }
}
