<?php

namespace Loremweb\Bundle\TicketmanagerBundle\Repository;

/**
 * visiteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class visiteurRepository extends \Doctrine\ORM\EntityRepository
{
}
